### ISSUE TITLE
It will not load.

### ISSUE THREAD

**Issue by CybernetiX-S3C** [mustafaozhan/GoogleIntegratedSystemConky#11]
conky: Syntax error (conkyKeepRc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: statfs64 '/data': No such file or directory
conky: desktop window (1c0ae90) is subwindow of root window (6aa)
conky: window type - override
conky: drawing to created window (0x5400001)
conky: drawing to double buffer
conky: forked to background, pid is 8273

  File "/usr/local/bin/gcalcli", line 199
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("ERROR: Missing module - %s" % e.args[0])?
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  228
  Current serial number in output stream:  229
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  518
  Current serial number in output stream:  524

**Comment by mustafaozhan** [comment]
Your problem is about installing dependencies with different version of python.
Please see [this](https://github.com/mustafaozhan/GoogleIntegratedSystemConky/issues/10#issuecomment-435326555) comment in order to solve your issue

**Comment by CybernetiX-S3C** [comment]
First off i did exactly that. Im not using opensuse. I am using Kali.


error is still the same

conky: Syntax error (conkyKeepRc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (1a00013) is subwindow of root window (6aa)
conky: window type - override
conky: drawing to created window (0x3800001)
conky: drawing to double buffer
conky: forked to background, pid is 12554
conky: statfs64 '/data': No such file or directory

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  2 (X_ChangeWindowAttributes)
  Serial number of failed request:  178
  Current serial number in output stream:  179
  File "/usr/local/bin/gcalcli", line 199
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  466
  Current serial number in output stream:  472

**Comment by CybernetiX-S3C** [comment]
Linux CybernetiX-S3C 4.18.0-kali3-amd64 #1 SMP Debian 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux

**Comment by CybernetiX-S3C** [comment]
Please stop closing issues that aren't fixed.

**Comment by mustafaozhan** [comment]
Hello,

I closed issue bec it is an installation problem not an issue. You still have incorrect version of gcalcli so that's why you have same errors. Please uninstall gcalcli and install it with python2 instead of python3 (look how it  is done for your distribution) than your problem will be solved.
