### ISSUE TITLE
plank folder was removed

### ISSUE THREAD

**Issue by louger143** [mustafaozhan/GoogleIntegratedSystemConky#12]
Hi @mustafaozhan , it seems that you remove the plank/ folder but in install.sh you specify a command 

```
sudo mv plank/gisc /usr/share/plank/themes/
```

which leads to error in installation.

Commit File: https://github.com/mustafaozhan/GoogleIntegratedSystemConky/commit/7e494dd5f824e32c32787287de51c348547bc9f4

**Comment by mustafaozhan** [comment]
Oh yea you are right, I will fix this issue when i will get my personal computer. 👍 Thank you
