### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by hrqmonteiro** [mustafaozhan/GoogleIntegratedSystemConky#13]
Hello, any of the commands you wrote on your execpi gcalcli doesnt work here, like the --military and so on. Here's the output on my terminal:

![2019-02-23-202917_738x343_scrot](https://user-images.githubusercontent.com/17055027/53292933-b52aea00-37a9-11e9-873f-e6d1197cf920.png)

**Comment by mustafaozhan** [comment]
Hello, Can you please share with me the followings,
- `gcalcli` version
- Your distribution
- which version `python` used by `gcalcli` installation

**Comment by mustafaozhan** [comment]
closed bec of not response long time
