### ISSUE TITLE
Error Output on launch after following instructions

### ISSUE THREAD

**Issue by manucote** [mustafaozhan/GoogleIntegratedSystemConky#14]
1. on a fresh install of the newest Manjaro Linux KDE Plasma

Installation output:
sudo pacman -S python-pip python2-pip ; yaourt -S conky-lua ; sudo pip3 install beautifulsoup4 requests lxml ; sudo pip2.7 install gcalcli ; git clone https://github.com/mustafaozhan/GoogleIntegratedSystemConky ; cd GoogleIntegratedSystemConky/ ; chmod +x install.sh && sh install.sh
[sudo] password for manu: 
warning: python-pip-18.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (24) python2-appdirs-1.4.3-2  python2-cachecontrol-0.12.5-4  python2-chardet-3.0.4-2  python2-colorama-0.4.1-1  python2-distlib-0.2.8-1
              python2-distro-1.4.0-1  python2-html5lib-1.0.1-3  python2-idna-2.8-1  python2-ipaddress-1.0.22-1  python2-lockfile-0.12.2-4  python2-msgpack-0.6.1-1
              python2-packaging-19.0-1  python2-pep517-0.5.0-1  python2-progress-1.5-1  python2-pyparsing-2.3.1-1  python2-pytoml-0.1.20-1  python2-requests-2.21.0-1
              python2-retrying-1.3.3-4  python2-setuptools-1:40.8.0-1  python2-six-1.12.0-1  python2-urllib3-1.24.1-2  python2-webencodings-0.5.1-2  python-pip-18.1-2
              python2-pip-18.1-2

Total Download Size:    2.11 MiB
Total Installed Size:  12.65 MiB
Net Upgrade Size:      11.68 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-pip-18.1-2-any                                                      251.5 KiB   273K/s 00:01 [###########################################################] 100%
 python2-appdirs-1.4.3-2-any                                                 13.3 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-pyparsing-2.3.1-1-any                                               89.7 KiB   116K/s 00:01 [###########################################################] 100%
 python2-six-1.12.0-1-any                                                    19.1 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-packaging-19.0-1-any                                                30.7 KiB  3.00M/s 00:00 [###########################################################] 100%
 python2-setuptools-1:40.8.0-1-any                                          278.2 KiB   201K/s 00:01 [###########################################################] 100%
 python2-urllib3-1.24.1-2-any                                               148.3 KiB   144K/s 00:01 [###########################################################] 100%
 python2-chardet-3.0.4-2-any                                                147.8 KiB   198K/s 00:01 [###########################################################] 100%
 python2-idna-2.8-1-any                                                      79.5 KiB   398K/s 00:00 [###########################################################] 100%
 python2-requests-2.21.0-1-any                                               82.2 KiB   222K/s 00:00 [###########################################################] 100%
 python2-pep517-0.5.0-1-any                                                  20.0 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-retrying-1.3.3-4-any                                                10.0 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-ipaddress-1.0.22-1-any                                              30.5 KiB  77.6K/s 00:00 [###########################################################] 100%
 python2-pip-18.1-2-any                                                     250.0 KiB   178K/s 00:01 [###########################################################] 100%
 python2-msgpack-0.6.1-1-x86_64                                              69.0 KiB   284K/s 00:00 [###########################################################] 100%
 python2-cachecontrol-0.12.5-4-any                                           27.1 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-colorama-0.4.1-1-any                                                21.9 KiB  7.12M/s 00:00 [###########################################################] 100%
 python2-distlib-0.2.8-1-any                                                312.4 KiB   151K/s 00:02 [###########################################################] 100%
 python2-distro-1.4.0-1-any                                                  31.9 KiB  10.4M/s 00:00 [###########################################################] 100%
 python2-webencodings-0.5.1-2-any                                            16.7 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-html5lib-1.0.1-3-any                                               181.0 KiB   156K/s 00:01 [###########################################################] 100%
 python2-lockfile-0.12.2-4-any                                               17.5 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-pytoml-0.1.20-1-any                                                 16.3 KiB  0.00B/s 00:00 [###########################################################] 100%
 python2-progress-1.5-1-any                                                  10.9 KiB  0.00B/s 00:00 [###########################################################] 100%
(24/24) checking keys in keyring                                                                     [###########################################################] 100%
(24/24) checking package integrity                                                                   [###########################################################] 100%
(24/24) loading package files                                                                        [###########################################################] 100%
(24/24) checking for file conflicts                                                                  [###########################################################] 100%
(24/24) checking available disk space                                                                [###########################################################] 100%
:: Processing package changes...
( 1/24) reinstalling python-pip                                                                      [###########################################################] 100%
( 2/24) installing python2-appdirs                                                                   [###########################################################] 100%
( 3/24) installing python2-pyparsing                                                                 [###########################################################] 100%
( 4/24) installing python2-six                                                                       [###########################################################] 100%
( 5/24) installing python2-packaging                                                                 [###########################################################] 100%
( 6/24) installing python2-setuptools                                                                [###########################################################] 100%
( 7/24) installing python2-msgpack                                                                   [###########################################################] 100%
( 8/24) installing python2-urllib3                                                                   [###########################################################] 100%
Optional dependencies for python2-urllib3
    python2-pysocks: SOCKS support
    python2-brotlipy: Brotli support
    python2-pyopenssl: security support
( 9/24) installing python2-chardet                                                                   [###########################################################] 100%
(10/24) installing python2-idna                                                                      [###########################################################] 100%
(11/24) installing python2-requests                                                                  [###########################################################] 100%
Optional dependencies for python2-requests
    python2-ndg-httpsclient: HTTPS requests with SNI support
    python2-grequests: asynchronous requests with gevent
    python2-pysocks: SOCKS proxy support
(12/24) installing python2-cachecontrol                                                              [###########################################################] 100%
Optional dependencies for python2-cachecontrol
    python2-lockfile: for the FileCache [pending]
(13/24) installing python2-colorama                                                                  [###########################################################] 100%
(14/24) installing python2-distlib                                                                   [###########################################################] 100%
(15/24) installing python2-distro                                                                    [###########################################################] 100%
(16/24) installing python2-webencodings                                                              [###########################################################] 100%
(17/24) installing python2-html5lib                                                                  [###########################################################] 100%
Optional dependencies for python2-html5lib
    python2-lxml: lxml treebuilder
    python2-genshi: genshi treewalker
(18/24) installing python2-lockfile                                                                  [###########################################################] 100%
(19/24) installing python2-pytoml                                                                    [###########################################################] 100%
(20/24) installing python2-pep517                                                                    [###########################################################] 100%
(21/24) installing python2-progress                                                                  [###########################################################] 100%
(22/24) installing python2-retrying                                                                  [###########################################################] 100%
(23/24) installing python2-ipaddress                                                                 [###########################################################] 100%
(24/24) installing python2-pip                                                                       [###########################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
bash: yaourt: command not found
Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 1.0MB/s 
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (2.21.0)
Collecting lxml
  Downloading https://files.pythonhosted.org/packages/66/20/49201c7bcb1c92942ac98658b09fb4a0c0dcd064d439489349bc5891207c/lxml-4.3.3-cp37-cp37m-manylinux1_x86_64.whl (5.7MB)
     |████████████████████████████████| 5.7MB 1.6MB/s 
Collecting soupsieve>=1.2 (from beautifulsoup4)
  Downloading https://files.pythonhosted.org/packages/c9/f8/e54b1d771ed4fab66b3fa1c178e137a3c73d84fb6f64329bddf0da5a371c/soupsieve-1.9-py2.py3-none-any.whl
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests) (2.8)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests) (1.24.1)
Installing collected packages: soupsieve, beautifulsoup4, lxml
Successfully installed beautifulsoup4-4.7.1 lxml-4.3.3 soupsieve-1.9
Collecting gcalcli
  Downloading https://files.pythonhosted.org/packages/ae/fd/28e4eeb79d1315b5120d1ea5490b5d990e7a538d6917127d7d1f7f9c1798/gcalcli-4.0.3.tar.gz (1.7MB)
     |████████████████████████████████| 1.7MB 161kB/s 
Collecting python-dateutil (from gcalcli)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
     |████████████████████████████████| 235kB 1.0MB/s 
Collecting google-api-python-client>=1.4 (from gcalcli)
  Downloading https://files.pythonhosted.org/packages/7a/84/ffde3c95d4162cdc8bae710fecc6873cccb05ac33afc3b2c925c74cc0150/google-api-python-client-1.7.8.tar.gz (141kB)
     |████████████████████████████████| 143kB 701kB/s 
Collecting httplib2 (from gcalcli)
  Downloading https://files.pythonhosted.org/packages/75/d0/f213003c9deec99fb4f46e54580b93a3b121c487d9d6d888fc12267eb2a2/httplib2-0.12.1.tar.gz (218kB)
     |████████████████████████████████| 225kB 1.3MB/s 
Collecting oauth2client (from gcalcli)
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
     |████████████████████████████████| 102kB 980kB/s 
Collecting parsedatetime (from gcalcli)
  Downloading https://files.pythonhosted.org/packages/1d/48/ac8d4c6239437592852e951bcb9438dc585f80c29777c391aef69c67dc79/parsedatetime-2.4-py2-none-any.whl (40kB)
     |████████████████████████████████| 40kB 1.6MB/s 
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from gcalcli) (1.12.0)
Collecting google-auth>=1.4.1 (from google-api-python-client>=1.4->gcalcli)
  Downloading https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl (73kB)
     |████████████████████████████████| 81kB 1.5MB/s 
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client>=1.4->gcalcli)
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.4->gcalcli)
  Downloading https://files.pythonhosted.org/packages/f6/25/66a49231b44409d7f07cfcf2506a8b070ce3c99fc47cc256bea833f24791/uritemplate-3.0.0-py2-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client->gcalcli)
  Downloading https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl (73kB)
     |████████████████████████████████| 81kB 670kB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client->gcalcli)
  Downloading https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl (66kB)
     |████████████████████████████████| 71kB 7.8MB/s 
Collecting rsa>=3.1.4 (from oauth2client->gcalcli)
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting future (from parsedatetime->gcalcli)
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
     |████████████████████████████████| 829kB 1.7MB/s 
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client>=1.4->gcalcli)
  Downloading https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Installing collected packages: python-dateutil, httplib2, pyasn1, rsa, cachetools, pyasn1-modules, google-auth, google-auth-httplib2, uritemplate, google-api-python-client, oauth2client, future, parsedatetime, gcalcli
  Running setup.py install for httplib2 ... done
  Running setup.py install for google-api-python-client ... done
  Running setup.py install for future ... done
  Running setup.py install for gcalcli ... done
Successfully installed cachetools-3.1.0 future-0.17.1 gcalcli-4.0.3 google-api-python-client-1.7.8 google-auth-1.6.3 google-auth-httplib2-0.0.3 httplib2-0.12.1 oauth2client-4.1.3 parsedatetime-2.4 pyasn1-0.4.5 pyasn1-modules-0.2.4 python-dateutil-2.8.0 rsa-4.0 uritemplate-3.0.0
Cloning into 'GoogleIntegratedSystemConky'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 321 (delta 8), reused 9 (delta 4), pack-reused 303
Receiving objects: 100% (321/321), 447.45 KiB | 821.00 KiB/s, done.
Resolving deltas: 100% (164/164), done.
mv: cannot move 'plank/gisc' to '/usr/share/plank/themes/': No such file or directory

-- added the gmail info

launch output:
conky: Syntax error (conkyKeepRc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: llua_do_call: function conky_clock_rings execution failed: attempt to call a nil value
conky: desktop window (2400013) is subwindow of root window (6aa)
conky: window type - override
conky: drawing to created window (0x4a00001)
conky: drawing to double buffer
conky: forked to background, pid is 19866
conky: statfs '/data': No such file or directory

conky: X Error: type 0 Display 5599a605fd40 XID 41943162 serial 166 error_code 8 request_code 2 minor_code 0 other Display: 5599a605fd40

usage: gcalcli [-h] [--default-calendar DEFAULTCALENDAR] [--calendar CALENDAR]
               [--refresh] [--client-id CLIENT_ID] [--conky] [--nocache]
               [--locale LOCALE] [--noincluderc]
               [--lineart {fancy,unicode,ascii}]
               [--config-folder CONFIG_FOLDER] [--nocolor]
               [--client-secret CLIENT_SECRET]
gcalcli: error: unrecognized arguments: --detail_location --nolineart --military
conky: llua_do_call: function conky_clock_rings execution failed: attempt to call a nil value
conky: X Error: type 0 Display 563e78d2b2e0 XID 42 serial 431 error_code 8 request_code 139 minor_code 4 other Display: 563e78d2b2e0

killall conky
conky: no process found

**Comment by mustafaozhan** [comment]
well, I see your problem now.
You have `Requirement already satisfied: ....`
Probably some other packages installed them  from repo in the past. I had same issue and I solved with going these mentioned (already satisfied ones) and deleting these folders. Then running my script again.
By this way  you will get them from `pip2.7`  and `pip3`. Not  the one Manjaro uses currently in their repos.
