### ISSUE TITLE
error not start

### ISSUE THREAD

**Issue by mubasir212** [mustafaozhan/GoogleIntegratedSystemConky#15]
how to fix no start
![Screenshot from 2019-10-10 02-32-07](https://user-images.githubusercontent.com/10860115/66513887-431fcf00-eb06-11e9-990b-59838790ea04.png)

**Comment by mustafaozhan** [comment]
can you provide your distro and desktop environment it doesn't seem like a error that will block the drawing . Probably it came to your desktop but not seeable due to configuration conflicts  with your DE

**Comment by jahorwitz** [comment]
I'm also having this issue. I'm running PopOS 19.10. What info do you need?

**Comment by jahorwitz** [comment]
> I'm also having this issue. I'm running PopOS 19.10. What info do you need?

This post helped me get passed this error: https://askubuntu.com/questions/543024/x-error-of-failed-request-badmatch-invalid-parameter-attributes-when-runing-c

**Comment by mustafaozhan** [comment]
@jahorwitz yes the Desktop environment you use may required the changes
```
own_window_type desktop
#own_window_type override
own_window_transparent yes
#own_window_transparent no
```

@jahorwitz does it solve the problem  for you ? @mubasir212  you can try same as well

**Comment by mustafaozhan** [comment]
closing no response
