### ISSUE TITLE
What is the name of the font from bottom right corner used to show the time ?

### ISSUE THREAD

**Issue by cata0309** [mustafaozhan/GoogleIntegratedSystemConky#16]
![image](https://user-images.githubusercontent.com/35623921/84025435-3c4aa400-a994-11ea-9f26-7816046deb76.png)

**Comment by mustafaozhan** [comment]
Hello,
As I remember you need to use `adapta` gtk and for font i was using `roboto`, btw this is XFCE desktop you also need to right click to clock and then choose preferences than change the layout to digital
