### ISSUE TITLE
Help on fixing install.sh errors

### ISSUE THREAD

**Issue by adminGodChryz** [mustafaozhan/GoogleIntegratedSystemConky#17]
`sh install.sh
mv: cannot move 'fonts/' to '/home/adminGodChryz/.local/share/fonts': Directory not empty
mv: cannot move 'plank/gisc' to '/usr/share/plank/themes/': No such file or directory
mv: cannot move 'GoogleIntegratedSystemConky/' to '/home/adminGodChryz/.config/GoogleIntegratedSystemConky': Directory not empty`

hi there! i want to try your theme, but it seems that i cant make it to yourk, would you mind helping me?

ive already fix some on the gcalcli but this i have no idea, should i remove those folders?

**Comment by adminGodChryz** [comment]
so iremoved all th folders that dont exist and created the ones that are requested and fireup install.sh and it reported no errors, but i cant see it on conky manager

**Comment by mustafaozhan** [comment]
Hello et's start from beginning, i think something went wrong during your installation. Which Distribution are you using ?

**Comment by adminGodChryz** [comment]
i am using mx linux sir

**Comment by mustafaozhan** [comment]
I do not have information about Mx Linux so the script that i shared will not work properly
Please check your package manager, you need to first install `conky`, `python3-pip` and `python-pip`

After Successfully install them please run 
```
sudo pip3 install beautifulsoup4 requests lxml
```
```
sudo pip install gcalcli
```

then you will need to run the script but as I can see from your logs you had problem in this place.
So please clone the repo
```
 git clone https://github.com/mustafaozhan/GoogleIntegratedSystemConky
``` 
Than open it
- copy `fonts` into `~/.local/share/`
- open `plank` folder copy `gisc` into `/usr/share/plank/themes/`
- move twice back and copy the repository folder `GoogleIntegratedSystemConky` into `~/.config/`

During last three operations if it will ask you `file already exists` please replace them.

then you will continue with rest of customisations

- If you want your picture on desktop. Go to the ~/.config/GoogleIntegratedSystemConky/background/ and choose a walpaper and add your profile picture in the circle (You can use Gimp as a editor and for good looking you can make it grayscale)

- If you want Google Calendar support In ~/.config/GoogleIntegratedSystemConky/config.xml put your google mail address and password for notes

Then  start with
```
sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start
```

- In first time a windows with your default browser will be openned and it will ask for your gmail permission for calendar. After that if it will print any error on the desktop kill conky with 
```killall conky``` than start it back with ```sh ~/.config/GoogleIntegratedSystemConky/gisc.sh start```

**Comment by adminGodChryz** [comment]
sorry for the late reply, just busy on school workloads,
just want to clarify that my system needs both python 2 and 3? and i need to install gcalcli with a python2-pip?

**Comment by mustafaozhan** [comment]
Yes exactly, since it is build on `python2` otherwise it will give you syntax errors during intallation

**Comment by adminGodChryz** [comment]
`sudo pip install gcalcli
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting gcalcli
  Using cached gcalcli-4.2.1.tar.gz (1.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-IpBt2R/gcalcli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-IpBt2R/gcalcli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mAfa9i
         cwd: /tmp/pip-install-IpBt2R/gcalcli/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-IpBt2R/gcalcli/setup.py", line 12
        print('Warning: No long description generated.', file=sys.stderr)
                                                             ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

im having this error

**Comment by mustafaozhan** [comment]
hmm `gcalcli` is not maintained  by me. On the other hand, It seems they moved to python3 already.|
Can you install with python3, this is their official [repo](https://github.com/insanum/gcalcli)

**Comment by adminGodChryz** [comment]
> hmm `gcalcli` is not maintained by me. On the other hand, It seems they moved to python3 already.|
> Can you install with python3, this is their official [repo](https://github.com/insanum/gcalcli)

that is what i did on my previous attempts before reporting the errors on the installation script
