### ISSUE TITLE
Install yaourt and git

### ISSUE THREAD

**Issue by archy-coder** [mustafaozhan/GoogleIntegratedSystemConky#19]
## This will be a helpful feature to add
The `yaourt` AUR helper is not installed by default, nor is git. 
In the `Arch Linux` section in [README.md](https://github.com/mustafaozhan/GoogleIntegratedSystemConky/blob/master/README.md#Installation)

**Comment by archy-coder** [comment]
I have also created a [pull request](https://github.com/mustafaozhan/GoogleIntegratedSystemConky/pull/20) for this issue.

**Comment by mustafaozhan** [comment]
@AryanMangale can you please check PR comments :)

**Comment by mustafaozhan** [comment]
@archy-coder will you address to the comments ?

**Comment by mustafaozhan** [comment]
Closed due to inactivity
