### ISSUE TITLE
Looking for only good keep and calendar widget

### ISSUE THREAD

**Issue by SyRaza** [mustafaozhan/GoogleIntegratedSystemConky#5]
Hi there, new to this whole thing. I was hoping you could upload the google keep and google calendar portions separately. I like your minimalist style with them. I checked out both conkyKeep and gcalcli that you credited but editing those is beyond my capabilities.

Thank you!

**Comment by mustafaozhan** [comment]
Hello,
As i understand you just want Google Keep and Google Calendar not any other extra information in your conky. So you need to change
`~/.config/GoogleIntegratedSystemConky/conkyrc`
with
```
#Conky Settings
background yes
update_interval 1

cpu_avg_samples 2
net_avg_samples 2

override_utf8_locale yes

double_buffer yes
no_buffers yes

text_buffer_size 2048

temperature_unit fahrenheit

#Window Specification
own_window no
own_window_type normal
own_window_transparent yes
own_window_argb_visual yes


border_inner_margin 0
border_outer_margin 0

# Adjust Resolution according to your screen
minimum_size 1600 900
maximum_width 1600

alignment tr
gap_x 0
gap_y 0

#Graphics Settings #
draw_shades no
draw_outline no
draw_borders no
draw_graph_borders no

#Text settings #
use_xft yes
xftfont monofur dreams:size=8
xftalpha 0.5

uppercase no
temperature_unit celsius

default_color ffffff

TEXT

${voffset 0}${voffset 0}${font monofur:pixelsize=14}${color ffffff}${execpi 1400  gcalcli --refresh --detail_location --nolineart --nocolor --military agenda "$(date)" }
```

Note that: 
`~/.config/GoogleIntegratedSystemConky/conkyrc` for Google Calendar configuration and in last line there is `${voffset 0}${voffset 0}` you can play with them for positioning in your desktop.(by default text arranged to the left)
`~/.config/GoogleIntegratedSystemConky/conkyKeepRc` for Google Keep and you can play with `gap_x 0
gap_y 611` to positioning on your desktop.(by default text arranged to the right)

Let me now after you play with them.

Regards

**Comment by mustafaozhan** [comment]
Issue closed because it is answered as a request. There is no feedback after it.
